"""
Django settings for books project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ENVIRONMENT = os.environ.get('ENVIRONMENT', default='development')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG', default=0))


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "https://smaple-bookstore-project.herokuapp.com/"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # disable serving staticfiles with staticfiles app entirely
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    "django.contrib.sites",

    #3rd party
    'crispy_forms',
    "allauth",
    "allauth.account",
    "debug_toolbar",

    # local
    'users.apps.UsersConfig',
    'pages.apps.PagesConfig',
    'booksapp.apps.BooksappConfig',
]

MIDDLEWARE = [
    # update caching
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # use whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",

    # caches entire site
    'django.middleware.cache.FetchFromCacheMiddleware',
    ]

ROOT_URLCONF = 'books.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'books.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'USER': os.environ.get('DATABASE_USER'),
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
# whitenoise storage compresses static files when running collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# authentication app
AUTH_USER_MODEL="users.CustomUser"

# auth views redirects
LOGIN_REDIRECT_URL="home"
Account_LOGOUT_REDIRECT="home"

# crispy forms settings
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#django-allauth config
SITE_ID = 1
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_USERNAME_REQUIRED = False # usernames are not required 
ACCOUNT_AUTHENTICATION_METHOD = 'email' # choose authentication method
ACCOUNT_EMAIL_REQUIRED=True # emails are required in forms
ACCOUNT_UNIQUE_EMAIL=True # emails are unique

# email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # new

DEFAULT_FROM_EMAIL = 'admin@djangbookstore.com'


# media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# however, since we’re running our web server within Docker an
# additional step is required so that it matches the machine address of Docker. Add
import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[:-1] + "1" for ip in ips]


# cache settings
# explicits setting default variables
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 604800
CACHE_MIDDLEARE_KEY_PREFIX = ''

# production settings
if ENVIRONMENT == 'production':
    # enable xss protection header
    SECURE_BROWSER_XSS_FILTER = True
    # prevent loading iframes 
    X_FRAME_OPTIONS = 'DENY' 
    # force non https requests to be redirected to http
    SECURE_SSL_REDIRECT = True
    # force browsers to only interact via https
    SECURE_HSTS_SECONDS = 3600 
    # force sub-domains to only interact via https
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # prevent browsers from guessing content-type
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # force authorization cookies over https
    SESSION_COOKIE_SECURE = True
    # force csrf cookie over https
    CSRF_COOKIE_SECURE = True
    # Set a tuple with two elements – the name of the header to look for and the required value
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

import dj_database_url
# get database config suing DATABASE_URL env variable
# and set persistent database connection limit to 500
# Persistent connections avoid the overhead of re-establishing a connection to the database in each request.
# They’re controlled by the CONN_MAX_AGE parameter which defines the maximum lifetime of a connection 
db_from_env = dj_database_url.config(conn_max_age=500)
# switch to heroku database
DATABASES['default'].update(db_from_env)
